### ISSUE TITLE
Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by M0rr155** [emilast/vscode-logfile-highlighter#627]
2024-09-16 09:12:58.590 [error] Error: [ExtensionListenerError] Extension 'emilast.LogFileHighlighter' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'get')
	at i.value (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:28731)
	at r.B (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.C (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:802)
	at r.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:1018)
	at E.$acceptModelChanged (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:86852)
	at y.S (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:5968)
	at y.Q (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:5734)
	at y.M (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:4767)
	at y.L (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:3602)
	at i.value (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:2297)
	at r.B (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:949)
	at a.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:14463)
	at i.value (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:184:8635)
	at r.B (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:949)
	at a.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:14463)
	at MessagePortMain.<anonymous> (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:184:6761)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)

**Comment by emilast** [comment]
Thanks for the report.

- What did you do for this to happen?
- Was this an observable error or did it only appear in the logs?
- What log file does the above error come from?

**Comment by M0rr155** [comment]
It happens when starting VSCode and it shows in de OUTPUT panel "Window".
So i think it is in one of the logs, but i am quite new to VSCode.
![image](https://github.com/user-attachments/assets/4ed4a6d3-39ad-484c-92c6-9cd414291da4)

**Comment by emilast** [comment]
I could not reproduce this error but I found one place where it could possibly happen. This should be fixed now, I hope. Feel free to confirm the resolution, or reopen this issue.

Thanks again for reporting.

**Comment by M0rr155** [comment]
unfortunately not solved:

2024-09-23 08:57:21.256 [error] [ExtensionListenerError] Extension 'emilast.LogFileHighlighter' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'get'): Error: [ExtensionListenerError] Extension 'emilast.LogFileHighlighter' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'get')
	at i.value (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:28731)
	at r.B (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.C (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:802)
	at r.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:1018)
	at E.$acceptModelChanged (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:86852)
	at y.S (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:5968)
	at y.Q (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:5734)
	at y.M (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:4767)
	at y.L (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:3602)
	at i.value (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:2297)
	at r.B (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:949)
	at a.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:14463)
	at i.value (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:184:8635)
	at r.B (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:949)
	at a.fire (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:14463)
	at MessagePortMain.<anonymous> (c:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:184:6761)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)

**Comment by emilast** [comment]
This is strange and I cannot repeat it on any of my computers.

Do you have any files left open in the workspace you're starting in? If you close all files and then restart VS Code, does this still happen?

Do you have other VS Code extensions installed?

As a last resort (if you want to spend a few minutes to help identify the problem) perhaps you could clone this repository, open the folder in VS Code and press F5 to start a second instance and debug the extension in the first instance? That should make it apparent where the problem occurs.

**Comment by M0rr155** [comment]
I paid attention to this problem the last week and i do not see it anymore.


Groeten,

Maurice
________________________________
Van: Emil Aström ***@***.***>
Verzonden: vrijdag 4 oktober 2024 23:20
Aan: emilast/vscode-logfile-highlighter ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [emilast/vscode-logfile-highlighter] Cannot read properties of undefined (reading 'get') (Issue #627)


This is strange and I cannot repeat it on any of my computers.

Do you have any files left open in the workspace you're starting in? If you close all files and then restart VS Code, does this still happen?

Do you have other VS Code extensions installed?

As a last resort (if you want to spend a few minutes to help identify the problem) perhaps you could clone this repository, open the folder in VS Code and press F5 to start a second instance and debug the extension in the first instance? That should make it apparent where the problem occurs.
